### ISSUE TITLE
Tweak wording of location copier question for clarity

### ISSUE THREAD

**Issue by JamesOHeaDLS** [epics-containers/services-template-helm#27]
I think the wording of the default location copier question should be made clearer.

Many of the questions refer to a 'beamline shortname', expecting an answer in the form 'i04', b16', etc.  However, although the location question also refers to beamline shortname, it expects an answer in the form 'bl04i', bl16b', etc

I suggest the wording could be changed to something like,

"At DLS this should be the beamline name in the form blxxy, or blank for the accelerator"

Maybe a placeholder could be added with an example name too?

**Comment by gilesknap** [comment]
The changes asked for here are done. Commit [d32245b](https://github.com/epics-containers/services-template-helm/commit/d32245b930dfa3eb7d713227f4cd61720e62dbee) ("refine copier questions") removed the "beamline shortname" wording from the `location` question. It now asks for the `blxxy` form and has a placeholder. See [`copier.yml` L98-108 on main](https://github.com/epics-containers/services-template-helm/blob/8132d00e15da9ecc177513273753c97d5de2827a/copier.yml#L98-L108):

```yaml
location:
  help: |
    Default location where these IOCs and services will run.

      At DLS this should blxxi for beamlines or one of srxxc, brxxc, linac for the accelerator
  placeholder: e.g. "bl21i" "bl16b" "bl01c" "sr03c" "linac"
```

(The help text is missing a "be" in "should blxxi", which can be fixed in passing.) Closing as completed.

_Triage comment drafted by Claude Code._
