### ISSUE TITLE
Rabbitmq enable metrics

### ISSUE THREAD

**Issue by ZohebShaikh** [epics-containers/services-template-helm#32]
Set up the monitoring stack to collect metrics from rabbitmq. Current config:

```yaml
metrics:
  enabled: true
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
```

**Tasks:**

* [ ] Ensure Prometheus is scraping metrics from the namespace
* [ ] Verify metrics appear in the monitoring dashboard
* [ ] Finalize and commit the config

**Comment by gilesknap** [comment]
The config in this issue (`metrics.enabled` / `metrics.podAnnotations`) is Bitnami chart syntax. Since [1fe7c77](https://github.com/epics-containers/services-template-helm/commit/1fe7c77) the template uses groundhog2k's `rabbitmq` chart, where the equivalent settings are:

```yaml
rabbitmq:
  prometheusPlugin:
    enabled: true          # adds the rabbitmq_prometheus plugin and the Service port 15692
  # Prometheus Operator:
  serviceMonitor:
    enabled: true          # scrapes /metrics; detailed/perObject endpoints are opt-in
  # or annotation-based scraping instead:
  # podAnnotations:
  #   prometheus.io/scrape: "true"
  #   prometheus.io/path: /metrics
  #   prometheus.io/port: "15692"
```

One catch: the template sets `service.type: LoadBalancer`, so turning on `prometheusPlugin` also exposes 15692 on the RabbitMQ load-balancer IP. The metrics would then be reachable from outside the namespace.

Which option fits depends on how the beamline clusters' monitoring stack discovers targets (ServiceMonitor or annotations), and that is the open question in the first task above. Once that is known, the values change is a few lines.

_Triage comment drafted by Claude Code._
